"""convert_tags_id_to_identity

Revision ID: 2716159fa3ea
Revises: 8aee17a93a6e
Create Date: 2025-12-17 19:40:19.541228

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2716159fa3ea'
down_revision: Union[str, Sequence[str], None] = '8aee17a93a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure the column is NOT NULL (Identity columns require this)
    op.alter_column('tags', 'id', nullable=False)

    # Add the Identity property to the existing column
    #    "GENERATED BY DEFAULT" allows you to manually specify an ID if you really want to
    op.execute(
        "ALTER TABLE tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY"
    )

    # Sync the new identity counter with existing data
    #    This finds the hidden sequence created by the Identity column and sets it
    #    to the current max(id) + 1.
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('tags', 'id'), 
            COALESCE(max(id), 0) + 1, 
            false
        ) FROM tags
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Remove the identity property, turning it back into a plain integer
    op.execute("ALTER TABLE tags ALTER COLUMN id DROP IDENTITY")
