"""added columns to payment_requests table for disputes

Revision ID: 32a0b3109cdc
Revises: 6ceca6c58d6b
Create Date: 2026-04-08 16:51:31.854657

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32a0b3109cdc'
down_revision: Union[str, Sequence[str], None] = '6ceca6c58d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('dispute_raised', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('payment_requests', sa.Column('dispute_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('payment_requests', sa.Column('dispute_raised_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payment_requests', sa.Column('dispute_admin_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_requests', 'dispute_admin_note')
    op.drop_column('payment_requests', 'dispute_raised_at')
    op.drop_column('payment_requests', 'dispute_reason')
    op.drop_column('payment_requests', 'dispute_raised')
    # ### end Alembic commands ###
