"""added listing models

Revision ID: 4f3f9f3ef0ec
Revises: 6cf25d388ba4
Create Date: 2025-12-03 21:38:37.151023

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f3f9f3ef0ec'
down_revision: Union[str, Sequence[str], None] = '6cf25d388ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('OFFER_SERVICE', 'SEARCH_SERVICE', 'SELL_PRODUCT', 'SEARCH_PRODUCT', 'OFFER_RENTAL', 'RIDE_SHARE', 'EVENT_WORKSHOP', name='listingcategory'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SOLD', 'DELETED', name='listingstatus'), nullable=False),
    sa.Column('title_original', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description_original', sa.String(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_de', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_hu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_de', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_hu', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('radius_km', sa.Integer(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_category'), 'listings', ['category'], unique=False)
    op.create_index(op.f('ix_listings_owner_id'), 'listings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_owner_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_category'), table_name='listings')
    op.drop_table('listings')
    op.drop_table('tags')
    # ### end Alembic commands ###
