"""improved invite code format and added used_by column

Revision ID: 611f1b77fc8c
Revises: 4f3f9f3ef0ec
Create Date: 2025-12-06 15:47:19.126269

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611f1b77fc8c'
down_revision: Union[str, Sequence[str], None] = '4f3f9f3ef0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('used_by_id', sa.Uuid(), nullable=True))
    op.alter_column('invites', 'code',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.create_foreign_key("fk_used_by_user", 'invites', 'users', ['used_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_used_by_user", 'invites', type_='foreignkey')
    op.alter_column('invites', 'code',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('invites', 'used_by_id')
    # ### end Alembic commands ###
