"""skipped migration for matrix fields

Revision ID: 6ceca6c58d6b
Revises: 4ae094e7f236
Create Date: 2026-03-29 14:29:35.955291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ceca6c58d6b'
down_revision: Union[str, Sequence[str], None] = '4ae094e7f236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('matrix_rooms_matrix_room_id_key'), 'matrix_rooms', type_='unique')
    op.drop_index(op.f('ix_matrix_rooms_matrix_room_id'), table_name='matrix_rooms')
    op.create_index(op.f('ix_matrix_rooms_matrix_room_id'), 'matrix_rooms', ['matrix_room_id'], unique=True)
    op.drop_constraint(op.f('matrix_user_credentials_user_id_key'), 'matrix_user_credentials', type_='unique')
    op.drop_index(op.f('ix_matrix_user_credentials_user_id'), table_name='matrix_user_credentials')
    op.create_index(op.f('ix_matrix_user_credentials_user_id'), 'matrix_user_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matrix_user_credentials_user_id'), table_name='matrix_user_credentials')
    op.create_index(op.f('ix_matrix_user_credentials_user_id'), 'matrix_user_credentials', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('matrix_user_credentials_user_id_key'), 'matrix_user_credentials', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_matrix_rooms_matrix_room_id'), table_name='matrix_rooms')
    op.create_index(op.f('ix_matrix_rooms_matrix_room_id'), 'matrix_rooms', ['matrix_room_id'], unique=False)
    op.create_unique_constraint(op.f('matrix_rooms_matrix_room_id_key'), 'matrix_rooms', ['matrix_room_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
