"""added banking service tables

Revision ID: 6cf25d388ba4
Revises: 6eac8a0c08dc
Create Date: 2025-11-30 21:11:45.287755

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cf25d388ba4'
down_revision: Union[str, Sequence[str], None] = '6eac8a0c08dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('TIME', 'REGIO', name='currency'), nullable=False),
    sa.Column('balance_time', sa.Integer(), nullable=False),
    sa.Column('balance_regio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_demurrage_calc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_type'), 'accounts', ['type'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('payment_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('creditor_id', sa.Uuid(), nullable=False),
    sa.Column('debtor_id', sa.Uuid(), nullable=False),
    sa.Column('amount_time', sa.Integer(), nullable=False),
    sa.Column('amount_regio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'EXECUTED', 'REJECTED', 'CANCELLED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['debtor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_requests_creditor_id'), 'payment_requests', ['creditor_id'], unique=False)
    op.create_index(op.f('ix_payment_requests_debtor_id'), 'payment_requests', ['debtor_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('amount_time', sa.Integer(), nullable=False),
    sa.Column('amount_regio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_request_id', sa.Uuid(), nullable=True),
    sa.Column('is_system_fee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_payment_request_id'), 'transactions', ['payment_request_id'], unique=False)
    op.create_index(op.f('ix_transactions_receiver_id'), 'transactions', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_transactions_sender_id'), 'transactions', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_sender_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_payment_request_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payment_requests_debtor_id'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_creditor_id'), table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_type'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
