"""changed tag id column from UUID to integer

Revision ID: 8aee17a93a6e
Revises: c70886fda011
Create Date: 2025-12-13 18:58:36.940026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8aee17a93a6e'
down_revision: Union[str, Sequence[str], None] = 'c70886fda011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the existing primary key constraint
    # Note: 'tags_pkey' is the default default naming convention in Postgres. 
    op.execute("ALTER TABLE tags DROP CONSTRAINT tags_pkey")

    #  Drop the old UUID 'id' column
    op.drop_column('tags', 'id')

    # Add the new Integer 'id' column
    # In Postgres, creating a column as SERIAL is equivalent to Integer + Sequence
    # But in SQLAlchemy/Alembic, we add it as Integer with autoincrement=True
    op.add_column('tags', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # Create the new Primary Key constraint
    op.create_primary_key('tags_pkey', 'tags', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the Integer primary key
    op.execute("ALTER TABLE tags DROP CONSTRAINT tags_pkey")

    # Drop the Integer 'id' column
    op.drop_column('tags', 'id')

    # Re-add the UUID 'id' column
    op.add_column('tags', sa.Column('id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=False))

    # Restore Primary Key
    op.create_primary_key('tags_pkey', 'tags', ['id'])
    # ### end Alembic commands ###
