"""added payment notes column to listings

Revision ID: a6eb8453c12d
Revises: e6afbae3ec11
Create Date: 2026-03-28 12:48:31.442066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6eb8453c12d'
down_revision: Union[str, Sequence[str], None] = 'e6afbae3ec11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('payment_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'payment_notes')
    # ### end Alembic commands ###
