from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # noqa: F401

# revision identifiers, used by Alembic.
revision: str = 'd81c46ddeda4'
down_revision: Union[str, Sequence[str], None] = '611f1b77fc8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    # Create verification status enum type first
    verification_status_enum = sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'ACTION_REQUIRED', name='verificationstatus')
    verification_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('users', sa.Column('notif_email_digest', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('notif_push', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('notif_newsletter', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('verification_status', verification_status_enum, nullable=False))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    
    # Define the Enum again so we can reference it for dropping
    verification_status_enum = sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'ACTION_REQUIRED', name='verificationstatus')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_at')
    
    op.drop_column('users', 'verification_status')
    
    op.drop_column('users', 'notif_newsletter')
    op.drop_column('users', 'notif_push')
    op.drop_column('users', 'notif_email_digest')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###

    # Drop the type from the database
    verification_status_enum.drop(op.get_bind())
