"""re-added expires_at column to invites

Revision ID: b70aa0a84f0a
Revises: cd507e8da2ba
Create Date: 2025-12-09 12:26:57.409363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70aa0a84f0a'
down_revision: Union[str, Sequence[str], None] = 'cd507e8da2ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
