"""added encrypted matrix password column and made address column nullable

Revision ID: c70886fda011
Revises: b70aa0a84f0a
Create Date: 2025-12-13 16:50:20.212291

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70886fda011'
down_revision: Union[str, Sequence[str], None] = 'b70aa0a84f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('matrix_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'matrix_password')
    # ### end Alembic commands ###
