"""added translated tag names fields

Revision ID: d3f3ec409e01
Revises: 81936d6a079a
Create Date: 2025-12-06 23:04:50.698505

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f3ec409e01'
down_revision: Union[str, Sequence[str], None] = '81936d6a079a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name_de', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tags', sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tags', sa.Column('name_hu', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'name_hu')
    op.drop_column('tags', 'name_en')
    op.drop_column('tags', 'name_de')
    # ### end Alembic commands ###
