"""added_self_referential_verification_fields

Revision ID: de4ab9507194
Revises: 2716159fa3ea
Create Date: 2026-01-03 21:41:56.452101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4ab9507194'
down_revision: Union[str, Sequence[str], None] = '2716159fa3ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key("fk_users_users_verified_by", 'users', 'users', ['verified_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_users_verified_by", 'users', type_='foreignkey')
    op.drop_column('users', 'verified_by_id')
    # ### end Alembic commands ###
