"""add_zip_registry

Revision ID: e7f363f2be6e
Revises: c1t2y3f4i5e6
Create Date: 2026-06-18 14:39:11.823124

"""
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

_CSV_PATH = Path(__file__).parent.parent.parent / "distance" / "ZIP-Hungary.csv"
_BATCH_SIZE = 500


# revision identifiers, used by Alembic.
revision: str = 'e7f363f2be6e'
down_revision: Union[str, Sequence[str], None] = 'c1t2y3f4i5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zip_registry',
    sa.Column('zip_code', sa.String(length=4), nullable=False),
    sa.Column('city_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('zip_code', 'city_name')
    )
    op.create_index('ix_zip_registry_zip_code', 'zip_registry', ['zip_code'], unique=False)

    conn = op.get_bind()
    if conn.execute(sa.text("SELECT COUNT(*) FROM zip_registry")).scalar() == 0:
        if _CSV_PATH.exists():
            batch: list[dict] = []
            seen: set[tuple[str, str]] = set()
            with open(_CSV_PATH, "r", encoding="utf-8-sig") as f:
                for line in f:
                    parts = line.strip().split(";", 1)
                    if len(parts) != 2:
                        continue
                    zip_code, city_name = parts[0].strip(), parts[1].strip()
                    if not zip_code or not city_name:
                        continue
                    # Skip duplicate (zip, city) pairs — the composite PK
                    # rejects them and the source CSV has a few.
                    if (zip_code, city_name) in seen:
                        continue
                    seen.add((zip_code, city_name))
                    batch.append({"zip_code": zip_code, "city_name": city_name})
                    if len(batch) >= _BATCH_SIZE:
                        conn.execute(sa.text("INSERT INTO zip_registry (zip_code, city_name) VALUES (:zip_code, :city_name)"), batch)
                        batch = []
            if batch:
                conn.execute(sa.text("INSERT INTO zip_registry (zip_code, city_name) VALUES (:zip_code, :city_name)"), batch)
            print(f"[INFO] Imported {_CSV_PATH.name} into zip_registry")
        else:
            print(f"[WARNING] {_CSV_PATH} not found — zip_registry will be empty")

    op.alter_column('users', 'zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_index('ix_zip_registry_zip_code', table_name='zip_registry')
    op.drop_table('zip_registry')
    # ### end Alembic commands ###
