"""ZIP-code visibility system

Revision ID: z1p2v3i4s5b6
Revises: 4ae094e7f236, a1b2c3d4e5f6
Create Date: 2026-05-14 00:00:00.000000

Implements the pre-computed ZIP-code distance visibility system:
  - Adds zip_distances table (populated from data coordinates.csv)
  - Adds post_visibilities junction table
  - Adds zip_code, d_class, available_until to listings
  - Removes obsolete radius_km, location_lat, location_lng from listings
  - Defaults existing listings to d_class = 'D5' (Nationwide)
  - Adds INACTIVE to listingstatus enum (if native PG type)
  - Adds zip_code to users
"""
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = "z1p2v3i4s5b6"
down_revision: Union[str, Sequence[str], None] = ("4ae094e7f236", "a1b2c3d4e5f6")
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Path to the distance CSV (relative to this file: ../../distance/data coordinates.csv)
_CSV_PATH = Path(__file__).parent.parent.parent / "distance" / "data coordinates.csv"
_BATCH_SIZE = 5_000


def upgrade() -> None:
    conn = op.get_bind()

    # ------------------------------------------------------------------
    # 1. Add INACTIVE to listingstatus enum (no-op if type doesn't exist)
    # ------------------------------------------------------------------
    conn.execute(sa.text("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_type WHERE typname = 'listingstatus') THEN
                ALTER TYPE listingstatus ADD VALUE IF NOT EXISTS 'INACTIVE';
            END IF;
        END $$;
    """))

    # ------------------------------------------------------------------
    # 2. Modify listings table
    # ------------------------------------------------------------------
    # Drop old geo columns if they still exist
    conn.execute(sa.text("""
        ALTER TABLE listings
            DROP COLUMN IF EXISTS radius_km,
            DROP COLUMN IF EXISTS location_lat,
            DROP COLUMN IF EXISTS location_lng
    """))

    # Add new columns if they don't exist yet
    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'listings' AND column_name = 'zip_code'
            ) THEN
                ALTER TABLE listings ADD COLUMN zip_code VARCHAR(10);
            END IF;
        END $$;
    """))

    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'listings' AND column_name = 'd_class'
            ) THEN
                ALTER TABLE listings ADD COLUMN d_class VARCHAR(2);
            END IF;
        END $$;
    """))

    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'listings' AND column_name = 'available_until'
            ) THEN
                ALTER TABLE listings ADD COLUMN available_until TIMESTAMPTZ;
            END IF;
        END $$;
    """))

    # Default existing listings to D5 (Nationwide) so they remain visible
    conn.execute(sa.text("UPDATE listings SET d_class = 'D5' WHERE d_class IS NULL"))

    # ------------------------------------------------------------------
    # 3. Add zip_code to users if not already present
    # ------------------------------------------------------------------
    conn.execute(sa.text("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'users' AND column_name = 'zip_code'
            ) THEN
                ALTER TABLE users ADD COLUMN zip_code VARCHAR(10);
            END IF;
        END $$;
    """))

    # ------------------------------------------------------------------
    # 4. Create zip_distances table (idempotent)
    # ------------------------------------------------------------------
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS zip_distances (
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            zip_from    VARCHAR(10) NOT NULL,
            zip_to      VARCHAR(10) NOT NULL,
            distance_km SMALLINT    NOT NULL
        )
    """))

    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_zip_distances_zip_from_km
        ON zip_distances (zip_from, distance_km)
    """))

    # ------------------------------------------------------------------
    # 5. Import distance data only if table is empty
    # ------------------------------------------------------------------
    row_count = conn.execute(sa.text("SELECT COUNT(*) FROM zip_distances")).scalar()

    if row_count == 0:
        if _CSV_PATH.exists():
            batch: list[dict] = []

            with open(_CSV_PATH, "r", encoding="utf-8") as f:
                for line in f:
                    parts = line.strip().split(";")
                    if len(parts) != 3:
                        continue
                    try:
                        batch.append(
                            {
                                "zip_from": parts[0].strip(),
                                "zip_to": parts[1].strip(),
                                "distance_km": int(float(parts[2].strip())),
                            }
                        )
                    except ValueError:
                        continue

                    if len(batch) >= _BATCH_SIZE:
                        conn.execute(
                            sa.text(
                                "INSERT INTO zip_distances (zip_from, zip_to, distance_km) "
                                "VALUES (:zip_from, :zip_to, :distance_km)"
                            ),
                            batch,
                        )
                        batch = []

            if batch:
                conn.execute(
                    sa.text(
                        "INSERT INTO zip_distances (zip_from, zip_to, distance_km) "
                        "VALUES (:zip_from, :zip_to, :distance_km)"
                    ),
                    batch,
                )
            print(f"[INFO] Imported distance data from {_CSV_PATH}")
        else:
            print(
                f"[WARNING] Distance CSV not found at {_CSV_PATH}. "
                "zip_distances table will be empty."
            )
    else:
        print(f"[INFO] zip_distances already has {row_count} rows — skipping import.")

    # ------------------------------------------------------------------
    # 6. Create post_visibilities table (idempotent)
    # ------------------------------------------------------------------
    conn.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS post_visibilities (
            post_id    UUID        NOT NULL,
            viewer_zip VARCHAR(10) NOT NULL,
            PRIMARY KEY (post_id, viewer_zip),
            FOREIGN KEY (post_id) REFERENCES listings(id) ON DELETE CASCADE
        )
    """))

    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_post_visibilities_viewer_zip
        ON post_visibilities (viewer_zip)
    """))

    conn.execute(sa.text("""
        CREATE INDEX IF NOT EXISTS ix_post_visibilities_post_id
        ON post_visibilities (post_id)
    """))


def downgrade() -> None:
    conn = op.get_bind()

    conn.execute(sa.text("DROP TABLE IF EXISTS post_visibilities"))
    conn.execute(sa.text("DROP TABLE IF EXISTS zip_distances"))

    conn.execute(sa.text("""
        ALTER TABLE users DROP COLUMN IF EXISTS zip_code
    """))

    conn.execute(sa.text("""
        ALTER TABLE listings
            DROP COLUMN IF EXISTS available_until,
            DROP COLUMN IF EXISTS d_class,
            DROP COLUMN IF EXISTS zip_code
    """))

    conn.execute(sa.text("""
        ALTER TABLE listings
            ADD COLUMN IF NOT EXISTS radius_km     INTEGER DEFAULT 10,
            ADD COLUMN IF NOT EXISTS location_lat  FLOAT,
            ADD COLUMN IF NOT EXISTS location_lng  FLOAT
    """))
